services:
  dim-red-torch:
    build: 
      context: .
      dockerfile: Dockerfile 
    image: asn-ae-image
    container_name: dim-red-container  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "8gb"
    tty: true
    stdin_open: true